const GET_TODOS_START = 'GET_TODOS_START';
const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
const GET_TODOS_FAIL = 'GET_TODOS_FAIL';

const ADD_TODO_START = 'ADD_TODO_START';
const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
const ADD_TODO_FAIL = 'ADD_TODO_FAIL';

const DELETE_TODO_START = 'DELETE_TODO_START';
const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
const DELETE_TODO_FAIL = 'DELETE_TODO_FAIL';

const EDIT_TODO_START = 'EDIT_TODO_START';
const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS';
const EDIT_TODO_FAIL = 'EDIT_TODO_FAIL';

export {
  GET_TODOS_SUCCESS,
  GET_TODOS_START,
  GET_TODOS_FAIL,
  ADD_TODO_SUCCESS,
  ADD_TODO_START,
  ADD_TODO_FAIL,
  DELETE_TODO_START,
  DELETE_TODO_SUCCESS,
  DELETE_TODO_FAIL,
  EDIT_TODO_FAIL,
  EDIT_TODO_SUCCESS,
  EDIT_TODO_START
};